---
title: "Betsy Rosalen HW 1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# HW 1

#### Question 1

Simplify the following expression.  Write the solution using rational exponents.

$$\left(\frac{64x \cdot y^{-2}}{x^{-2} \cdot y}\right)^\frac{-1}{2}$$



#### Question 2

If $f(x)  = \sqrt{x + 5}$ and $g(x) = \frac{3}{x}$ , find  $f(x) \cdot g(x)$.



#### Question 3
Find the break-even point(s) for the revenue and cost functions below.
$$R(x) =	24.2x - 0.2x^2$$
$$C(x)	=	13x + 147$$


#### Question 4
Find the derivative for the following function.
$$y = 9x^{8.2}$$


#### Question 5
Find the derivative for $f(x) = -4x^5 - 3x^4 - 4x^3 - 3$.  

#### Question 6
A pole that is 4264 feet long is leaning against a building.  The bottom of the pole is moving away from the wall at a rate of 2 ft./sec.  How fast is the top of the pole moving down the wall when the top is 3480 feet off the ground?

#### Question 7
Use the Product Rule or Quotient Rule to find the derivative.
$$f(x) = \frac{3x^8 - x^5}{2x^8 + 2}$$

#### Question 8
Consider the function:
$$f(x) = 4x + 25x^{-1}$$
**Step 1.** Find the critical values of the function. 

**Step 2.** Use the First Derivative Test to find any local extrema.  Write any local extrema as an ordered pair. 

#### Question 9
Evaluate $\frac{dy}{dx}$ at $x = 1$ for the function below.
$$y = -9u^2 + 7u + 4 \text{ where } u = -3x^3  + 3x + 6$$



#### Question 10
Consider the following function:
$$f(x) = (x + 5)(x + 4)^2$$

**Step 1.** Determine $f'(x)$ and $f''(x)$ .  


**Step 2.** Determine where the function is increasing and decreasing.  Write your answers in interval notation. 


**Step 3.** Determine where the function is concave up and concave down.  Write your answers in interval notation. 


**Step 4.** Find the x-values of any local minima, maxima, and inflection points.  



#### Question 11
Consider the function:
$$f(x) = -7x^2 - 84x - 140$$

**Step 1.** Find the second derivative of the given function. 


**Step 2.** Use the Second Derivative Test to locate any local maximum or minimum points in the graph of the given function.  Express your answer(s) as ordered pairs. 



#### Question 12
A beauty supply store expects to sell 100 flat irons during the next year.  It costs \$1.20 to store one flat iron for one year.  There is a fixed cost of \$15  for each order.  Find the lot size and the number of orders per year that will minimize inventory costs. 


#### Question 13
Find the derivative of the given expression.
$$y = \frac{18x}{ln(x^4)}$$



#### Question 14
Consider the following function:
$$f(x) = -5x^3 e^x$$

**Step 1.** Find the first derivative of the above function. 


**Step 2.** Find the second derivative of the above function. 



#### Question 15
Evaluate the definite integral below.  Write your answer in exact form or rounded to two decimal places.
	
$$\int_{-3}^{1} \left(8\sqrt[3]{(8x + 5)^2}\right) dx$$



#### Question 16
Solve the differential equation given below.
$$\frac{dy}{dx} = -4(-3 - y)$$



#### Question 17
The marginal cost of a product is given by $238 + \frac{298}{\sqrt x}$ dollars per unit, where $x$ is the number of units produced. The current level of production is 137 units weekly.  If the level of production is increased to 232 units weekly, find the increase in the total costs.  Round your answer to the nearest cent.


#### Question 18
Find the Taylor polynomial of degree 5 near $x = 1$  for the following function.
$$y = \sqrt{4x - 3}$$ 


